export const LEGO_SETS_UPDATE_LIST = 'LEGO_SETS_UPDATE_LIST';
export const LEGO_SET_UPDATE_ITEM = 'LEGO_SET_UPDATE_ITEM';
export const LEGO_SETS_FETCH_STATE = 'LEGO_SETS_FETCH_STATE';
export const QUERY_PARAMS_UPDATE_LIST = 'QUERY_PARAMS_UPDATE_LIST';
